import { nanoid } from '../store.js'

// Templates pré-definidos. Cada um recebe o tamanho lógico do stage {w,h} e a
// paleta atual, e devolve { background, elements } adaptado ao formato.
// Coordenadas em espaço lógico (ver lib/stage.js).

const pick = (palette, i, fallback) => palette[i] || fallback

export const TEMPLATES = [
  {
    key: 'capa',
    name: 'Capa Bold',
    build: ({ w, h }, palette) => {
      const bg = pick(palette, 0, '#0E1116')
      return {
        background: bg,
        elements: [
          {
            id: nanoid(),
            type: 'rect',
            x: w * 0.08,
            y: h * 0.62,
            width: w * 0.16,
            height: 8,
            fill: pick(palette, 2, '#6C5CE7'),
            cornerRadius: 4,
            rotation: 0,
            opacity: 1,
          },
          {
            id: nanoid(),
            type: 'text',
            x: w * 0.08,
            y: h * 0.3,
            width: w * 0.84,
            text: 'SEU TÍTULO\nEM DESTAQUE',
            fontFamily: 'Bebas Neue',
            fontSize: Math.round(h * 0.11),
            fontStyle: 'normal',
            fill: '#FFFFFF',
            align: 'left',
            lineHeight: 0.95,
            letterSpacing: 1,
            rotation: 0,
            opacity: 1,
          },
          {
            id: nanoid(),
            type: 'text',
            x: w * 0.08,
            y: h * 0.66,
            width: w * 0.84,
            text: 'Subtítulo de apoio explicando o post em uma linha.',
            fontFamily: 'Inter',
            fontSize: Math.round(h * 0.03),
            fontStyle: 'normal',
            fill: '#C9CDD6',
            align: 'left',
            lineHeight: 1.3,
            letterSpacing: 0,
            rotation: 0,
            opacity: 1,
          },
        ],
      }
    },
  },
  {
    key: 'citacao',
    name: 'Citação',
    build: ({ w, h }, palette) => ({
      background: pick(palette, 1, '#101418'),
      elements: [
        {
          id: nanoid(),
          type: 'text',
          x: w * 0.1,
          y: h * 0.12,
          width: w * 0.8,
          text: '“',
          fontFamily: 'Playfair Display',
          fontSize: Math.round(h * 0.18),
          fontStyle: 'bold',
          fill: pick(palette, 2, '#6C5CE7'),
          align: 'left',
          lineHeight: 1,
          letterSpacing: 0,
          rotation: 0,
          opacity: 1,
        },
        {
          id: nanoid(),
          type: 'text',
          x: w * 0.1,
          y: h * 0.3,
          width: w * 0.8,
          text: 'Uma frase de impacto que prende a atenção do seu público.',
          fontFamily: 'Playfair Display',
          fontSize: Math.round(h * 0.055),
          fontStyle: 'normal',
          fill: '#FFFFFF',
          align: 'left',
          lineHeight: 1.25,
          letterSpacing: 0,
          rotation: 0,
          opacity: 1,
        },
        {
          id: nanoid(),
          type: 'text',
          x: w * 0.1,
          y: h * 0.82,
          width: w * 0.8,
          text: '— @seu_perfil',
          fontFamily: 'Inter',
          fontSize: Math.round(h * 0.028),
          fontStyle: 'bold',
          fill: '#C9CDD6',
          align: 'left',
          lineHeight: 1.2,
          letterSpacing: 1,
          rotation: 0,
          opacity: 1,
        },
      ],
    }),
  },
  {
    key: 'dica',
    name: 'Dica / Lista',
    build: ({ w, h }, palette) => ({
      background: pick(palette, 0, '#F5F3FF'),
      elements: [
        {
          id: nanoid(),
          type: 'text',
          x: w * 0.08,
          y: h * 0.1,
          width: w * 0.84,
          text: '3 DICAS RÁPIDAS',
          fontFamily: 'Montserrat',
          fontSize: Math.round(h * 0.06),
          fontStyle: 'bold',
          fill: '#1A1430',
          align: 'left',
          lineHeight: 1.1,
          letterSpacing: 1,
          rotation: 0,
          opacity: 1,
        },
        {
          id: nanoid(),
          type: 'text',
          x: w * 0.08,
          y: h * 0.32,
          width: w * 0.84,
          text: '1.  Primeiro ponto importante\n\n2.  Segundo ponto importante\n\n3.  Terceiro ponto importante',
          fontFamily: 'Inter',
          fontSize: Math.round(h * 0.035),
          fontStyle: 'normal',
          fill: '#2B2440',
          align: 'left',
          lineHeight: 1.4,
          letterSpacing: 0,
          rotation: 0,
          opacity: 1,
        },
      ],
    }),
  },
  {
    key: 'minimal',
    name: 'Minimal',
    build: ({ w, h }, palette) => ({
      background: pick(palette, 0, '#FFFFFF'),
      elements: [
        {
          id: nanoid(),
          type: 'text',
          x: w * 0.1,
          y: h * 0.44,
          width: w * 0.8,
          text: 'menos\né mais.',
          fontFamily: 'Poppins',
          fontSize: Math.round(h * 0.08),
          fontStyle: 'bold',
          fill: pick(palette, 3, '#111111'),
          align: 'center',
          lineHeight: 1.05,
          letterSpacing: 0,
          rotation: 0,
          opacity: 1,
        },
      ],
    }),
  },
]
